import { z } from "zod";
import { Envelope } from "./envelope";
export declare const IntentTypeEnum: z.ZodEnum<["BUY_SETUP", "SELL_SETUP", "CLOSE_LONG", "CLOSE_SHORT", "CLOSE"]>;
export declare const IntentStatusEnum: z.ZodEnum<["PENDING", "VALIDATED", "REJECTED", "EXECUTED", "EXECUTED_PARTIAL", "EXPIRED", "FAILED"]>;
export declare const IntentPayloadSchemaV1: z.ZodEffects<z.ZodEffects<z.ZodObject<{
    schema_version: z.ZodOptional<z.ZodString>;
    signal_id: z.ZodString;
    source: z.ZodOptional<z.ZodString>;
    symbol: z.ZodString;
    direction: z.ZodEffects<z.ZodNumber, number, number>;
    type: z.ZodEnum<["BUY_SETUP", "SELL_SETUP", "CLOSE_LONG", "CLOSE_SHORT", "CLOSE"]>;
    entry_zone: z.ZodOptional<z.ZodArray<z.ZodNumber, "many">>;
    stop_loss: z.ZodOptional<z.ZodNumber>;
    child_fills: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    policy_hash: z.ZodOptional<z.ZodString>;
    take_profits: z.ZodOptional<z.ZodArray<z.ZodNumber, "many">>;
    size: z.ZodNumber;
    status: z.ZodEnum<["PENDING", "VALIDATED", "REJECTED", "EXECUTED", "EXECUTED_PARTIAL", "EXPIRED", "FAILED"]>;
    t_signal: z.ZodOptional<z.ZodNumber>;
    timestamp: z.ZodOptional<z.ZodNumber>;
    t_analysis: z.ZodOptional<z.ZodNumber>;
    t_decision: z.ZodOptional<z.ZodNumber>;
    t_ingress: z.ZodOptional<z.ZodNumber>;
    t_exchange: z.ZodOptional<z.ZodNumber>;
    max_slippage_bps: z.ZodOptional<z.ZodNumber>;
    rejection_reason: z.ZodOptional<z.ZodString>;
    regime_state: z.ZodOptional<z.ZodNumber>;
    phase: z.ZodOptional<z.ZodNumber>;
    exchange: z.ZodOptional<z.ZodString>;
    position_mode: z.ZodOptional<z.ZodString>;
    metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
    confidence: z.ZodOptional<z.ZodNumber>;
    leverage: z.ZodOptional<z.ZodNumber>;
    expected_impact_bps: z.ZodOptional<z.ZodNumber>;
    fill_feasibility: z.ZodOptional<z.ZodNumber>;
    velocity: z.ZodOptional<z.ZodNumber>;
    trap_type: z.ZodOptional<z.ZodString>;
    parent_strategy: z.ZodOptional<z.ZodString>;
}, "passthrough", z.ZodTypeAny, z.objectOutputType<{
    schema_version: z.ZodOptional<z.ZodString>;
    signal_id: z.ZodString;
    source: z.ZodOptional<z.ZodString>;
    symbol: z.ZodString;
    direction: z.ZodEffects<z.ZodNumber, number, number>;
    type: z.ZodEnum<["BUY_SETUP", "SELL_SETUP", "CLOSE_LONG", "CLOSE_SHORT", "CLOSE"]>;
    entry_zone: z.ZodOptional<z.ZodArray<z.ZodNumber, "many">>;
    stop_loss: z.ZodOptional<z.ZodNumber>;
    child_fills: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    policy_hash: z.ZodOptional<z.ZodString>;
    take_profits: z.ZodOptional<z.ZodArray<z.ZodNumber, "many">>;
    size: z.ZodNumber;
    status: z.ZodEnum<["PENDING", "VALIDATED", "REJECTED", "EXECUTED", "EXECUTED_PARTIAL", "EXPIRED", "FAILED"]>;
    t_signal: z.ZodOptional<z.ZodNumber>;
    timestamp: z.ZodOptional<z.ZodNumber>;
    t_analysis: z.ZodOptional<z.ZodNumber>;
    t_decision: z.ZodOptional<z.ZodNumber>;
    t_ingress: z.ZodOptional<z.ZodNumber>;
    t_exchange: z.ZodOptional<z.ZodNumber>;
    max_slippage_bps: z.ZodOptional<z.ZodNumber>;
    rejection_reason: z.ZodOptional<z.ZodString>;
    regime_state: z.ZodOptional<z.ZodNumber>;
    phase: z.ZodOptional<z.ZodNumber>;
    exchange: z.ZodOptional<z.ZodString>;
    position_mode: z.ZodOptional<z.ZodString>;
    metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
    confidence: z.ZodOptional<z.ZodNumber>;
    leverage: z.ZodOptional<z.ZodNumber>;
    expected_impact_bps: z.ZodOptional<z.ZodNumber>;
    fill_feasibility: z.ZodOptional<z.ZodNumber>;
    velocity: z.ZodOptional<z.ZodNumber>;
    trap_type: z.ZodOptional<z.ZodString>;
    parent_strategy: z.ZodOptional<z.ZodString>;
}, z.ZodTypeAny, "passthrough">, z.objectInputType<{
    schema_version: z.ZodOptional<z.ZodString>;
    signal_id: z.ZodString;
    source: z.ZodOptional<z.ZodString>;
    symbol: z.ZodString;
    direction: z.ZodEffects<z.ZodNumber, number, number>;
    type: z.ZodEnum<["BUY_SETUP", "SELL_SETUP", "CLOSE_LONG", "CLOSE_SHORT", "CLOSE"]>;
    entry_zone: z.ZodOptional<z.ZodArray<z.ZodNumber, "many">>;
    stop_loss: z.ZodOptional<z.ZodNumber>;
    child_fills: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    policy_hash: z.ZodOptional<z.ZodString>;
    take_profits: z.ZodOptional<z.ZodArray<z.ZodNumber, "many">>;
    size: z.ZodNumber;
    status: z.ZodEnum<["PENDING", "VALIDATED", "REJECTED", "EXECUTED", "EXECUTED_PARTIAL", "EXPIRED", "FAILED"]>;
    t_signal: z.ZodOptional<z.ZodNumber>;
    timestamp: z.ZodOptional<z.ZodNumber>;
    t_analysis: z.ZodOptional<z.ZodNumber>;
    t_decision: z.ZodOptional<z.ZodNumber>;
    t_ingress: z.ZodOptional<z.ZodNumber>;
    t_exchange: z.ZodOptional<z.ZodNumber>;
    max_slippage_bps: z.ZodOptional<z.ZodNumber>;
    rejection_reason: z.ZodOptional<z.ZodString>;
    regime_state: z.ZodOptional<z.ZodNumber>;
    phase: z.ZodOptional<z.ZodNumber>;
    exchange: z.ZodOptional<z.ZodString>;
    position_mode: z.ZodOptional<z.ZodString>;
    metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
    confidence: z.ZodOptional<z.ZodNumber>;
    leverage: z.ZodOptional<z.ZodNumber>;
    expected_impact_bps: z.ZodOptional<z.ZodNumber>;
    fill_feasibility: z.ZodOptional<z.ZodNumber>;
    velocity: z.ZodOptional<z.ZodNumber>;
    trap_type: z.ZodOptional<z.ZodString>;
    parent_strategy: z.ZodOptional<z.ZodString>;
}, z.ZodTypeAny, "passthrough">>, z.objectOutputType<{
    schema_version: z.ZodOptional<z.ZodString>;
    signal_id: z.ZodString;
    source: z.ZodOptional<z.ZodString>;
    symbol: z.ZodString;
    direction: z.ZodEffects<z.ZodNumber, number, number>;
    type: z.ZodEnum<["BUY_SETUP", "SELL_SETUP", "CLOSE_LONG", "CLOSE_SHORT", "CLOSE"]>;
    entry_zone: z.ZodOptional<z.ZodArray<z.ZodNumber, "many">>;
    stop_loss: z.ZodOptional<z.ZodNumber>;
    child_fills: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    policy_hash: z.ZodOptional<z.ZodString>;
    take_profits: z.ZodOptional<z.ZodArray<z.ZodNumber, "many">>;
    size: z.ZodNumber;
    status: z.ZodEnum<["PENDING", "VALIDATED", "REJECTED", "EXECUTED", "EXECUTED_PARTIAL", "EXPIRED", "FAILED"]>;
    t_signal: z.ZodOptional<z.ZodNumber>;
    timestamp: z.ZodOptional<z.ZodNumber>;
    t_analysis: z.ZodOptional<z.ZodNumber>;
    t_decision: z.ZodOptional<z.ZodNumber>;
    t_ingress: z.ZodOptional<z.ZodNumber>;
    t_exchange: z.ZodOptional<z.ZodNumber>;
    max_slippage_bps: z.ZodOptional<z.ZodNumber>;
    rejection_reason: z.ZodOptional<z.ZodString>;
    regime_state: z.ZodOptional<z.ZodNumber>;
    phase: z.ZodOptional<z.ZodNumber>;
    exchange: z.ZodOptional<z.ZodString>;
    position_mode: z.ZodOptional<z.ZodString>;
    metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
    confidence: z.ZodOptional<z.ZodNumber>;
    leverage: z.ZodOptional<z.ZodNumber>;
    expected_impact_bps: z.ZodOptional<z.ZodNumber>;
    fill_feasibility: z.ZodOptional<z.ZodNumber>;
    velocity: z.ZodOptional<z.ZodNumber>;
    trap_type: z.ZodOptional<z.ZodString>;
    parent_strategy: z.ZodOptional<z.ZodString>;
}, z.ZodTypeAny, "passthrough">, z.objectInputType<{
    schema_version: z.ZodOptional<z.ZodString>;
    signal_id: z.ZodString;
    source: z.ZodOptional<z.ZodString>;
    symbol: z.ZodString;
    direction: z.ZodEffects<z.ZodNumber, number, number>;
    type: z.ZodEnum<["BUY_SETUP", "SELL_SETUP", "CLOSE_LONG", "CLOSE_SHORT", "CLOSE"]>;
    entry_zone: z.ZodOptional<z.ZodArray<z.ZodNumber, "many">>;
    stop_loss: z.ZodOptional<z.ZodNumber>;
    child_fills: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    policy_hash: z.ZodOptional<z.ZodString>;
    take_profits: z.ZodOptional<z.ZodArray<z.ZodNumber, "many">>;
    size: z.ZodNumber;
    status: z.ZodEnum<["PENDING", "VALIDATED", "REJECTED", "EXECUTED", "EXECUTED_PARTIAL", "EXPIRED", "FAILED"]>;
    t_signal: z.ZodOptional<z.ZodNumber>;
    timestamp: z.ZodOptional<z.ZodNumber>;
    t_analysis: z.ZodOptional<z.ZodNumber>;
    t_decision: z.ZodOptional<z.ZodNumber>;
    t_ingress: z.ZodOptional<z.ZodNumber>;
    t_exchange: z.ZodOptional<z.ZodNumber>;
    max_slippage_bps: z.ZodOptional<z.ZodNumber>;
    rejection_reason: z.ZodOptional<z.ZodString>;
    regime_state: z.ZodOptional<z.ZodNumber>;
    phase: z.ZodOptional<z.ZodNumber>;
    exchange: z.ZodOptional<z.ZodString>;
    position_mode: z.ZodOptional<z.ZodString>;
    metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
    confidence: z.ZodOptional<z.ZodNumber>;
    leverage: z.ZodOptional<z.ZodNumber>;
    expected_impact_bps: z.ZodOptional<z.ZodNumber>;
    fill_feasibility: z.ZodOptional<z.ZodNumber>;
    velocity: z.ZodOptional<z.ZodNumber>;
    trap_type: z.ZodOptional<z.ZodString>;
    parent_strategy: z.ZodOptional<z.ZodString>;
}, z.ZodTypeAny, "passthrough">>, {
    t_signal: number;
    entry_zone: number[];
    take_profits: number[];
    symbol: string;
    type: "BUY_SETUP" | "SELL_SETUP" | "CLOSE_LONG" | "CLOSE_SHORT" | "CLOSE";
    status: "PENDING" | "VALIDATED" | "REJECTED" | "EXECUTED" | "EXECUTED_PARTIAL" | "EXPIRED" | "FAILED";
    signal_id: string;
    direction: number;
    child_fills: string[];
    size: number;
    exchange?: string | undefined;
    confidence?: number | undefined;
    phase?: number | undefined;
    metadata?: Record<string, any> | undefined;
    schema_version?: string | undefined;
    source?: string | undefined;
    stop_loss?: number | undefined;
    policy_hash?: string | undefined;
    timestamp?: number | undefined;
    t_analysis?: number | undefined;
    t_decision?: number | undefined;
    t_ingress?: number | undefined;
    t_exchange?: number | undefined;
    max_slippage_bps?: number | undefined;
    rejection_reason?: string | undefined;
    regime_state?: number | undefined;
    position_mode?: string | undefined;
    leverage?: number | undefined;
    expected_impact_bps?: number | undefined;
    fill_feasibility?: number | undefined;
    velocity?: number | undefined;
    trap_type?: string | undefined;
    parent_strategy?: string | undefined;
}, z.objectInputType<{
    schema_version: z.ZodOptional<z.ZodString>;
    signal_id: z.ZodString;
    source: z.ZodOptional<z.ZodString>;
    symbol: z.ZodString;
    direction: z.ZodEffects<z.ZodNumber, number, number>;
    type: z.ZodEnum<["BUY_SETUP", "SELL_SETUP", "CLOSE_LONG", "CLOSE_SHORT", "CLOSE"]>;
    entry_zone: z.ZodOptional<z.ZodArray<z.ZodNumber, "many">>;
    stop_loss: z.ZodOptional<z.ZodNumber>;
    child_fills: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    policy_hash: z.ZodOptional<z.ZodString>;
    take_profits: z.ZodOptional<z.ZodArray<z.ZodNumber, "many">>;
    size: z.ZodNumber;
    status: z.ZodEnum<["PENDING", "VALIDATED", "REJECTED", "EXECUTED", "EXECUTED_PARTIAL", "EXPIRED", "FAILED"]>;
    t_signal: z.ZodOptional<z.ZodNumber>;
    timestamp: z.ZodOptional<z.ZodNumber>;
    t_analysis: z.ZodOptional<z.ZodNumber>;
    t_decision: z.ZodOptional<z.ZodNumber>;
    t_ingress: z.ZodOptional<z.ZodNumber>;
    t_exchange: z.ZodOptional<z.ZodNumber>;
    max_slippage_bps: z.ZodOptional<z.ZodNumber>;
    rejection_reason: z.ZodOptional<z.ZodString>;
    regime_state: z.ZodOptional<z.ZodNumber>;
    phase: z.ZodOptional<z.ZodNumber>;
    exchange: z.ZodOptional<z.ZodString>;
    position_mode: z.ZodOptional<z.ZodString>;
    metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
    confidence: z.ZodOptional<z.ZodNumber>;
    leverage: z.ZodOptional<z.ZodNumber>;
    expected_impact_bps: z.ZodOptional<z.ZodNumber>;
    fill_feasibility: z.ZodOptional<z.ZodNumber>;
    velocity: z.ZodOptional<z.ZodNumber>;
    trap_type: z.ZodOptional<z.ZodString>;
    parent_strategy: z.ZodOptional<z.ZodString>;
}, z.ZodTypeAny, "passthrough">>;
export type IntentPayloadV1 = z.infer<typeof IntentPayloadSchemaV1>;
export type IntentMessage = Envelope<IntentPayloadV1>;
export declare function validateIntentPayload(payload: unknown): {
    valid: boolean;
    errors: string[];
    data?: IntentPayloadV1;
};
export declare function createIntentMessage(payload: IntentPayloadV1, producer: string, correlationId?: string): IntentMessage;
//# sourceMappingURL=intentSchema.d.ts.map