/**
 * MarketTradeV1 - Normalized trade event schema
 *
 * Published by Hunter from all venue WebSocket feeds.
 * Used for market data aggregation, analytics, and downstream consumers.
 */
import { z } from 'zod';
import { InstrumentType, VenueId } from '../types/venues.js';

/**
 * Taker side of the trade
 */
export const TakerSideSchema = z.enum(['buy', 'sell', 'unknown']);
export type TakerSide = z.infer<typeof TakerSideSchema>;

/**
 * MarketTradeV1 Zod Schema
 *
 * Canonical normalized trade event format across all venues.
 */
export const MarketTradeV1Schema = z.object({
  // Schema version for additive changes
  v: z.literal(1),

  // ISO8601 timestamp when event was generated by Hunter
  ts: z.string().datetime(),

  // Venue identifier
  venue: z.nativeEnum(VenueId),

  // Normalized symbol (e.g., "BTC/USDT", "BTC/USDT:PERP")
  symbol: z.string().min(1),

  // Raw exchange symbol (for debugging/reconciliation)
  raw_symbol: z.string().min(1),

  // Trade timestamp from exchange (epoch ms)
  exchange_ts: z.number().int(),

  // Trade price
  price: z.string(), // String to preserve decimal precision

  // Trade size/quantity
  size: z.string(), // String to preserve decimal precision

  // Which side was the taker (aggressor)
  taker_side: TakerSideSchema,

  // Exchange trade ID (if available)
  trade_id: z.string().optional(),

  // Instrument type
  instrument_type: z.nativeEnum(InstrumentType),

  // Optional: quote asset (for fee calculation)
  quote_asset: z.string().optional(),

  // Optional: base asset
  base_asset: z.string().optional(),
});

export type MarketTradeV1 = z.infer<typeof MarketTradeV1Schema>;

/**
 * Parse and validate a MarketTradeV1 message
 * @throws ZodError if validation fails
 */
export function parseMarketTradeV1(data: unknown): MarketTradeV1 {
  return MarketTradeV1Schema.parse(data);
}

/**
 * Safe parse that returns success/error result
 */
export function safeParseMarketTradeV1(
  data: unknown,
): z.SafeParseReturnType<unknown, MarketTradeV1> {
  return MarketTradeV1Schema.safeParse(data);
}
