#!/bin/bash
set -e

# Risk Policy Deduplication Guard
# Ensures that services/titan-execution-rs/src/risk_policy.json is NOT committed to git.
# It should only exist as a build artifact copied from packages/shared/risk_policy.json.

echo "🔍 Checking for duplicate Risk Policy files..."

DUPLICATE_FILE="services/titan-execution-rs/src/risk_policy.json"

if git ls-files --error-unmatch "$DUPLICATE_FILE" > /dev/null 2>&1; then
    echo "❌ FATAL: Duplicate Risk Policy detected in git index!"
    echo "   File '$DUPLICATE_FILE' must be removed from git."
    echo "   It is auto-generated by build.rs from packages/shared/risk_policy.json."
    echo "   Action: git rm --cached $DUPLICATE_FILE && echo '$DUPLICATE_FILE' >> .gitignore"
    exit 1
else
    echo "✅ No duplicate risk policy tracked in git."
    exit 0
fi
