import * as fs from "fs";
import * as path from "path";
import { program } from "commander";
import {
    DoraIncidentClassification,
    DoraIncidentSchema,
    DoraIncidentStatus,
} from "../../services/shared/src/schemas/DoraIncident";
import { v4 as uuidv4 } from "uuid";
import { z } from "zod";

const ARTIFACTS_DIR = "artifacts/compliance/incidents";

program
    .name("report-incident")
    .description("Generate a DORA-compliant incident report")
    .option("-t, --title <title>", "Incident title")
    .option("-d, --desc <description>", "Incident description")
    .option(
        "-c, --class <classification>",
        "Classification: MAJOR or SIGNIFICANT",
    )
    .option(
        "-s, --status <status>",
        "Status: DETECTED, INVESTIGATING, MITIGATED, RESOLVED",
    )
    .option("--root-cause <cause>", "Root cause analysis")
    .option(
        "--services <services>",
        "Comma-separated list of affected services",
    )
    .option("--loss <cents>", "Estimated financial loss in cents", parseInt)
    .action((options) => {
        run(options);
    });

function run(options: any) {
    // Ensure artifacts dir exists
    if (!fs.existsSync(ARTIFACTS_DIR)) {
        fs.mkdirSync(ARTIFACTS_DIR, { recursive: true });
    }

    const services = options.services
        ? options.services.split(",")
        : ["unknown"];

    const incidentData = {
        incidentId: uuidv4(),
        title: options.title || "Untitled Incident",
        description: options.desc || "No description provided.",
        detectionTime: new Date().toISOString(),
        classification: options.class || "SIGNIFICANT",
        status: options.status || "DETECTED",
        affectedServices: services,
        rootCause: options.rootCause,
        estimatedLossCents: options.loss,
        isReportable: (options.class === "MAJOR"), // Simple heuristic
    };

    try {
        const validated = DoraIncidentSchema.parse(incidentData);
        const filename = `${
            new Date().toISOString().split("T")[0]
        }_${validated.incidentId}.md`;
        const filepath = path.join(ARTIFACTS_DIR, filename);

        const markdown = `
# DORA Incident Report: ${validated.title}

| Field | Value |
|-------|-------|
| **ID** | \`${validated.incidentId}\` |
| **Date** | ${validated.detectionTime} |
| **Classification** | **${validated.classification}** |
| **Status** | ${validated.status} |
| **Reportable (Art. 19)** | ${validated.isReportable ? "YES" : "NO"} |

## Description
${validated.description}

## Affected Services
${validated.affectedServices.map((s) => `- ${s}`).join("\n")}

## Root Cause
${validated.rootCause || "Pending Investigation"}

## Financial Impact
${
            validated.estimatedLossCents
                ? `$${(validated.estimatedLossCents / 100).toFixed(2)}`
                : "Not assessed"
        }

---
*Generated by Titan Compliance Automation*
    `.trim();

        fs.writeFileSync(filepath, markdown);
        console.log(`✅ Incident report generated: ${filepath}`);

        if (validated.isReportable) {
            console.warn(
                "⚠️  This incident is classified as MAJOR and requires regulatory reporting under DORA Article 19.",
            );
        }
    } catch (error) {
        if (error instanceof z.ZodError) {
            console.error(
                "❌ Validation Failed:",
                JSON.stringify((error as any).issues || error, null, 2),
            );
        } else {
            console.error("❌ Error:", error);
        }
        process.exit(1);
    }
}

program.parse();
