name: Local Setup
description: "Sets up Node.js environment, caches dependencies, and handles toolchain bootstrapping."

inputs:
  node-version:
    description: "Node.js version to use"
    required: false
    default: '22.19.0'
  npm-version:
    description: "NPM version to use"
    required: false
    default: '11.6.2'
  cache-key-suffix:
    description: "Suffix for cache generation"
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.0.2
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        cache-dependency-path: '**/package-lock.json'

    - name: Pin npm version
      shell: bash
      run: npm install -g npm@${{ inputs.npm-version }}

    - name: Restore Turbo cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.0.1
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ inputs.node-version }}-${{ hashFiles('package-lock.json', 'turbo.json') }}${{ inputs.cache-key-suffix }}
        restore-keys: |
          ${{ runner.os }}-turbo-${{ inputs.node-version }}-

    - name: Install dependencies (Root)
      shell: bash
      run: npm ci
