name: titan-trading-system
region: ams

# =============================================================================
# TITAN TRADING SYSTEM - DIGITALOCEAN APP PLATFORM
# =============================================================================

services:
  # ---------------------------------------------------------------------------
  # TITAN CONSOLE - Public Web Dashboard (only public-facing service)
  # ---------------------------------------------------------------------------
  - name: titan-console
    source_dir: /services/titan-console
    dockerfile_path: services/titan-console/Dockerfile
    github:
      repo: peycheff-com/titan-trading-system
      branch: main
      deploy_on_push: true
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: VITE_API_URL
        value: "${titan-brain.PRIVATE_URL}"
      - key: VITE_WS_URL
        value: "${titan-brain.PRIVATE_URL}"

  # ---------------------------------------------------------------------------
  # TITAN BRAIN - Phase 5 Master Orchestrator (Internal)
  # ---------------------------------------------------------------------------
  - name: titan-brain
    source_dir: /services/titan-brain
    dockerfile_path: services/titan-brain/Dockerfile
    github:
      repo: peycheff-com/titan-trading-system
      branch: main
      deploy_on_push: true
    internal_ports:
      - 3100
    instance_count: 1
    instance_size_slug: professional-xs
    health_check:
      http_path: /health
      port: 3100
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3100"
      - key: HOST
        value: "0.0.0.0"
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_URL
        scope: RUN_TIME
        type: SECRET
      - key: NATS_URL
        scope: RUN_TIME
        type: SECRET
      - key: HMAC_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: LOG_LEVEL
        value: "info"
      - key: DEPLOYMENT_ENVIRONMENT
        value: "production"
      - key: SERVICE_NAME
        value: "titan-brain"

  # ---------------------------------------------------------------------------
  # TITAN EXECUTION (Rust) - High-Performance Order Execution (Internal)
  # ---------------------------------------------------------------------------
  - name: titan-execution
    source_dir: /services/titan-execution-rs
    dockerfile_path: services/titan-execution-rs/Dockerfile
    github:
      repo: peycheff-com/titan-trading-system
      branch: main
      deploy_on_push: true
    internal_ports:
      - 3002
    instance_count: 1
    instance_size_slug: professional-xs
    health_check:
      http_path: /health
      port: 3002
    envs:
      - key: RUST_LOG
        value: "info"
      - key: PORT
        value: "3002"
      - key: NATS_URL
        scope: RUN_TIME
        type: SECRET
      - key: BINANCE_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: BINANCE_API_SECRET
        scope: RUN_TIME
        type: SECRET

  # ---------------------------------------------------------------------------
  # TITAN AI QUANT - Gemini AI Parameter Optimization (Internal)
  # ---------------------------------------------------------------------------
  - name: titan-ai-quant
    source_dir: /services/titan-ai-quant
    dockerfile_path: services/titan-ai-quant/Dockerfile
    github:
      repo: peycheff-com/titan-trading-system
      branch: main
      deploy_on_push: true
    internal_ports:
      - 8082
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health
      port: 8082
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8082"
      - key: NATS_URL
        scope: RUN_TIME
        type: SECRET
      - key: GEMINI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: DEPLOYMENT_ENVIRONMENT
        value: "production"
      - key: SERVICE_NAME
        value: "titan-ai-quant"

  # ---------------------------------------------------------------------------
  # PHASE 1: SCAVENGER - High Leverage Trap Detection (Internal)
  # ---------------------------------------------------------------------------
  - name: titan-scavenger
    source_dir: /services/titan-phase1-scavenger
    dockerfile_path: services/titan-phase1-scavenger/Dockerfile
    github:
      repo: peycheff-com/titan-trading-system
      branch: main
      deploy_on_push: true
    internal_ports:
      - 8081
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health
      port: 8081
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8081"
      - key: BRAIN_URL
        value: "${titan-brain.PRIVATE_URL}"
      - key: DEPLOYMENT_ENVIRONMENT
        value: "production"
      - key: SERVICE_NAME
        value: "titan-scavenger"

  # ---------------------------------------------------------------------------
  # PHASE 2: HUNTER - Holographic Market Analysis (Internal)
  # ---------------------------------------------------------------------------
  - name: titan-hunter
    source_dir: /services/titan-phase2-hunter
    dockerfile_path: services/titan-phase2-hunter/Dockerfile
    github:
      repo: peycheff-com/titan-trading-system
      branch: main
      deploy_on_push: true
    internal_ports:
      - 8083
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health
      port: 8083
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8083"
      - key: BRAIN_URL
        value: "${titan-brain.PRIVATE_URL}"
      - key: DEPLOYMENT_ENVIRONMENT
        value: "production"
      - key: SERVICE_NAME
        value: "titan-hunter"

  # ---------------------------------------------------------------------------
  # PHASE 3: SENTINEL - Market-Neutral Basis Arbitrage (Internal)
  # ---------------------------------------------------------------------------
  - name: titan-sentinel
    source_dir: /services/titan-phase3-sentinel
    dockerfile_path: services/titan-phase3-sentinel/Dockerfile
    github:
      repo: peycheff-com/titan-trading-system
      branch: main
      deploy_on_push: true
    internal_ports:
      - 8084
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health
      port: 8084
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8084"
      - key: BRAIN_URL
        value: "${titan-brain.PRIVATE_URL}"
      - key: DEPLOYMENT_ENVIRONMENT
        value: "production"
      - key: SERVICE_NAME
        value: "titan-sentinel"

# =============================================================================
# MANAGED DATABASES (Create in DigitalOcean Console)
# 1. PostgreSQL - For titan-brain persistence
# 2. Redis - For caching (optional)
# Add connection strings as app secrets after creation.
# =============================================================================
