/**
 * Signal Types for Titan Phase 3 - The Sentinel
 * 
 * Defines trading signals, thresholds, and basis classification types.
 */

/**
 * Trading signal action types
 */
export type SignalAction = 'EXPAND' | 'CONTRACT' | 'HOLD';

/**
 * Trading signal generated by the Statistical Engine
 */
export interface Signal {
  /** Trading pair symbol (e.g., 'BTCUSDT') */
  symbol: string;
  /** Recommended action based on basis analysis */
  action: SignalAction;
  /** Current basis value (perp - spot) / spot */
  basis: number;
  /** Z-Score of current basis relative to rolling window */
  zScore: number;
  /** Confidence level of the signal (0-1) */
  confidence: number;
  /** Unix timestamp in milliseconds */
  timestamp: number;
}

/**
 * Signal generation thresholds
 */
export interface SignalThresholds {
  /** Z-Score threshold for EXPAND signal (default: +2.0) */
  expandZScore: number;
  /** Z-Score threshold for CONTRACT signal (default: 0.0) */
  contractZScore: number;
  /** Basis threshold for vacuum arbitrage (default: -0.5%) */
  vacuumBasis: number;
  /** Minimum confidence required to act on signal (default: 0.7) */
  minConfidence: number;
}

/**
 * Default signal thresholds
 */
export const DEFAULT_SIGNAL_THRESHOLDS: SignalThresholds = {
  expandZScore: 2.0,
  contractZScore: 0.0,
  vacuumBasis: -0.005, // -0.5%
  minConfidence: 0.7,
};

/**
 * Vacuum arbitrage opportunity detected during liquidation events
 */
export interface VacuumOpportunity {
  /** Trading pair symbol */
  symbol: string;
  /** Current basis (negative indicates discount) */
  basis: number;
  /** Current spot price */
  spotPrice: number;
  /** Current perpetual price */
  perpPrice: number;
  /** Estimated liquidation volume in USD */
  liquidationVolume: number;
  /** Expected profit from convergence */
  expectedProfit: number;
  /** Confidence level of the opportunity */
  confidence: number;
}

/**
 * Active vacuum arbitrage position
 */
export interface VacuumPosition {
  /** Trading pair symbol */
  symbol: string;
  /** Basis at entry */
  entryBasis: number;
  /** Spot entry price */
  spotEntry: number;
  /** Perpetual entry price */
  perpEntry: number;
  /** Position size in base asset */
  size: number;
  /** Entry timestamp */
  entryTime: number;
  /** Target basis for exit (typically 0 or positive) */
  targetBasis: number;
}
