/**
 * MorningBriefingDisplay Component
 * 
 * Displays the morning briefing generated by the nightly optimization job.
 * Shows date, summary, top insights, and pending proposals.
 * Includes a dismiss action to hide the briefing.
 * 
 * Implementation: Task 14
 * Requirements: 6.4
 */

import React from 'react';
import { Box, Text } from 'ink';
import type { MorningBriefing, Insight, OptimizationProposal, ValidationReport } from '../types/index.js';

export interface MorningBriefingDisplayProps {
  /** The morning briefing data */
  briefing: MorningBriefing;
  /** Whether the briefing is visible */
  visible: boolean;
  /** Callback when user dismisses the briefing */
  onDismiss?: () => void;
}

/**
 * Format a date string for display
 */
function formatDate(dateStr: string): string {
  try {
    const date = new Date(dateStr);
    return date.toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  } catch {
    return dateStr;
  }
}

/**
 * Format confidence as percentage
 */
function formatConfidence(confidence: number): string {
  return `${(confidence * 100).toFixed(0)}%`;
}

/**
 * Format PnL value
 */
function formatPnL(pnl: number): string {
  const sign = pnl >= 0 ? '+' : '';
  return `${sign}$${pnl.toFixed(2)}`;
}

/**
 * Format win rate as percentage
 */
function formatWinRate(winRate: number): string {
  return `${(winRate * 100).toFixed(1)}%`;
}

/**
 * InsightItem Component - Displays a single insight
 */
function InsightItem({ insight, index }: { insight: Insight; index: number }): React.ReactElement {
  return (
    <Box flexDirection="column" marginLeft={1} marginBottom={1}>
      <Box>
        <Text color="cyan">{index + 1}. </Text>
        <Text bold>{insight.topic}</Text>
        <Text dimColor> ({formatConfidence(insight.confidence)} confidence)</Text>
      </Box>
      <Box marginLeft={3}>
        <Text wrap="wrap">{insight.text}</Text>
      </Box>
      {insight.affectedSymbols && insight.affectedSymbols.length > 0 && (
        <Box marginLeft={3}>
          <Text dimColor>Symbols: {insight.affectedSymbols.join(', ')}</Text>
        </Box>
      )}
    </Box>
  );
}

/**
 * ProposalSummary Component - Displays a proposal summary
 */
function ProposalSummary({ 
  proposal, 
  validation, 
  index 
}: { 
  proposal: OptimizationProposal; 
  validation: ValidationReport; 
  index: number;
}): React.ReactElement {
  const pnlColor = validation.deltas.pnlDeltaPercent >= 0 ? 'green' : 'red';
  
  return (
    <Box flexDirection="column" marginLeft={1} marginBottom={1}>
      <Box>
        <Text color="yellow">{index + 1}. </Text>
        <Text bold>{proposal.targetKey}</Text>
      </Box>
      <Box marginLeft={3}>
        <Text dimColor>Change: </Text>
        <Text color="red">{String(proposal.currentValue)}</Text>
        <Text dimColor> → </Text>
        <Text color="green">{String(proposal.suggestedValue)}</Text>
      </Box>
      <Box marginLeft={3}>
        <Text dimColor>Expected PnL: </Text>
        <Text color={pnlColor}>
          {proposal.expectedImpact.pnlImprovement >= 0 ? '+' : ''}
          {proposal.expectedImpact.pnlImprovement.toFixed(1)}%
        </Text>
        <Text dimColor> | Confidence: </Text>
        <Text>{formatConfidence(proposal.expectedImpact.confidenceScore)}</Text>
      </Box>
    </Box>
  );
}

/**
 * PerformanceSummarySection Component
 */
function PerformanceSummarySection({ 
  summary 
}: { 
  summary: MorningBriefing['performanceSummary'];
}): React.ReactElement {
  const pnlColor = summary.pnl >= 0 ? 'green' : 'red';
  const winRateColor = summary.winRate >= 0.5 ? 'green' : summary.winRate >= 0.4 ? 'yellow' : 'red';
  
  return (
    <Box flexDirection="row" marginTop={1}>
      <Box marginRight={3}>
        <Text dimColor>Trades: </Text>
        <Text bold>{summary.totalTrades}</Text>
      </Box>
      <Box marginRight={3}>
        <Text dimColor>Win Rate: </Text>
        <Text bold color={winRateColor}>{formatWinRate(summary.winRate)}</Text>
      </Box>
      <Box>
        <Text dimColor>PnL: </Text>
        <Text bold color={pnlColor}>{formatPnL(summary.pnl)}</Text>
      </Box>
    </Box>
  );
}

/**
 * MorningBriefingDisplay Component
 * 
 * Displays the morning briefing in a dedicated section.
 * Shows date, summary, top insights, pending proposals, and performance summary.
 * 
 * Requirement 6.4: Display the morning briefing if available on console start
 */
export function MorningBriefingDisplay({
  briefing,
  visible,
  onDismiss,
}: MorningBriefingDisplayProps): React.ReactElement | null {
  if (!visible) {
    return null;
  }

  const hasInsights = briefing.topInsights.length > 0;
  const hasProposals = briefing.pendingProposals.length > 0;

  return (
    <Box 
      flexDirection="column" 
      borderStyle="double" 
      borderColor="magenta" 
      padding={1}
      marginBottom={1}
    >
      {/* Header */}
      <Box justifyContent="space-between">
        <Box>
          <Text bold color="magenta">🌅 MORNING BRIEFING</Text>
          <Text dimColor> - {formatDate(briefing.date)}</Text>
        </Box>
        <Text dimColor>[D] Dismiss</Text>
      </Box>

      {/* Summary */}
      <Box marginTop={1}>
        <Text wrap="wrap">{briefing.summary}</Text>
      </Box>

      {/* Performance Summary */}
      <PerformanceSummarySection summary={briefing.performanceSummary} />

      {/* Top Insights Section */}
      {hasInsights && (
        <Box flexDirection="column" marginTop={1}>
          <Text bold color="cyan">📊 Top Insights:</Text>
          {briefing.topInsights.map((insight, idx) => (
            <InsightItem key={insight.id ?? idx} insight={insight} index={idx} />
          ))}
        </Box>
      )}

      {/* Pending Proposals Section */}
      {hasProposals && (
        <Box flexDirection="column" marginTop={1}>
          <Text bold color="yellow">⚡ Pending Optimizations:</Text>
          {briefing.pendingProposals.map(({ proposal, validation }, idx) => (
            <ProposalSummary 
              key={proposal.id ?? idx} 
              proposal={proposal} 
              validation={validation} 
              index={idx} 
            />
          ))}
          <Box marginTop={1}>
            <Text dimColor>Press [A] to open AI Advisor and review proposals</Text>
          </Box>
        </Box>
      )}

      {/* No content message */}
      {!hasInsights && !hasProposals && (
        <Box marginTop={1}>
          <Text dimColor>No significant patterns detected overnight.</Text>
        </Box>
      )}
    </Box>
  );
}

export default MorningBriefingDisplay;
